# lib('util', ['util.c'], ['util.h'], [])

# lib('users', ['users.c'], ['users.h'], ['util'])

# lib('tweets', ['tweets.c'], ['tweets.h'], ['users', 'util'])

# test('userstest', ['userstest.c'], ['users'])

test('tweetstest', ['tweetstest.c'], ['tweets'])